	.align 2
DirectSoundWaveData_sc88pro_glockenspiel::
	.incbin "sound/direct_sound_samples/sc88pro_glockenspiel.bin"

	.align 2
DirectSoundWaveData_sc88pro_organ2::
	.incbin "sound/direct_sound_samples/sc88pro_organ2.bin"

	.align 2
DirectSoundWaveData_sc88pro_fretless_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fretless_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_slap_bass::
	.incbin "sound/direct_sound_samples/sc88pro_slap_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_synth_bass::
	.incbin "sound/direct_sound_samples/sc88pro_synth_bass.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani::
	.incbin "sound/direct_sound_samples/sc88pro_timpani.bin"

	.align 2
DirectSoundWaveData_classical_choir_voice_ahhs::
	.incbin "sound/direct_sound_samples/classical_choir_voice_ahhs.bin"

	.align 2
DirectSoundWaveData_sd90_classical_oboe::
	.incbin "sound/direct_sound_samples/sd90_classical_oboe.bin"

	.align 2
DirectSoundWaveData_unused_sd90_oboe::
	.incbin "sound/direct_sound_samples/unused_sd90_oboe.bin"

	.align 2
DirectSoundWaveData_unused_guitar_separates_power_chord::
	.incbin "sound/direct_sound_samples/unused_guitar_separates_power_chord.bin"

	.align 2
DirectSoundWaveData_unused_sc88pro_unison_slap::
	.incbin "sound/direct_sound_samples/unused_sc88pro_unison_slap.bin"

	.align 2
DirectSoundWaveData_unknown_snare::
	.incbin "sound/direct_sound_samples/unknown_snare.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_ohtsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_ohtsuzumi.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_hyoushigi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_hyoushigi.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_kick::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_kick.bin"

	.align 2
DirectSoundWaveData_sc88pro_rnd_snare::
	.incbin "sound/direct_sound_samples/sc88pro_rnd_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_tr909_hand_clap::
	.incbin "sound/direct_sound_samples/sc88pro_tr909_hand_clap.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_snare::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_snare.bin"

	.align 2
DirectSoundWaveData_unused_sc55_tom::
	.incbin "sound/direct_sound_samples/unused_sc55_tom.bin"

	.align 2
DirectSoundWaveData_unknown_close_hihat::
	.incbin "sound/direct_sound_samples/unknown_close_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_open_hihat::
	.incbin "sound/direct_sound_samples/unknown_open_hihat.bin"

	.align 2
DirectSoundWaveData_unknown_bell::
	.incbin "sound/direct_sound_samples/unknown_bell.bin"

	.align 2
DirectSoundWaveData_sc88pro_tambourine::
	.incbin "sound/direct_sound_samples/sc88pro_tambourine.bin"

	.align 2
DirectSoundWaveData_trinity_cymbal_crash::
	.incbin "sound/direct_sound_samples/trinity_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_orchestra_cymbal_crash::
	.incbin "sound/direct_sound_samples/sc88pro_orchestra_cymbal_crash.bin"

	.align 2
DirectSoundWaveData_sc88pro_mute_high_conga::
	.incbin "sound/direct_sound_samples/sc88pro_mute_high_conga.bin"

	.align 2
DirectSoundWaveData_sc88pro_open_low_conga::
	.incbin "sound/direct_sound_samples/sc88pro_open_low_conga.bin"

	.align 2
DirectSoundWaveData_drum_and_percussion_kick::
	.incbin "sound/direct_sound_samples/drum_and_percussion_kick.bin"

	.align 2
DirectSoundWaveData_sd90_solo_snare::
	.incbin "sound/direct_sound_samples/sd90_solo_snare.bin"

	.align 2
DirectSoundWaveData_sd90_ambient_tom::
	.incbin "sound/direct_sound_samples/sd90_ambient_tom.bin"

	.align 2
DirectSoundWaveData_dance_drums_ride_bell::
	.incbin "sound/direct_sound_samples/dance_drums_ride_bell.bin"

	.align 2
DirectSoundWaveData_sd90_cowbell::
	.incbin "sound/direct_sound_samples/sd90_cowbell.bin"

	.align 2
DirectSoundWaveData_unused_heart_of_asia_indian_drum::
	.incbin "sound/direct_sound_samples/unused_heart_of_asia_indian_drum.bin"

	.align 2
DirectSoundWaveData_sd90_open_triangle::
	.incbin "sound/direct_sound_samples/sd90_open_triangle.bin"

	.align 2
DirectSoundWaveData_sc88pro_jingle_bell::
	.incbin "sound/direct_sound_samples/sc88pro_jingle_bell.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_atarigane::
	.incbin "sound/direct_sound_samples/ethnic_flavours_atarigane.bin"

	.align 2
DirectSoundWaveData_sc88pro_taiko::
	.incbin "sound/direct_sound_samples/sc88pro_taiko.bin"

	.align 2
DirectSoundWaveData_ethnic_flavours_kotsuzumi::
	.incbin "sound/direct_sound_samples/ethnic_flavours_kotsuzumi.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_48::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_48.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_60::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_72::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_piano1_84::
	.incbin "sound/direct_sound_samples/sc88pro_piano1_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_60::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_72::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_string_ensemble_84::
	.incbin "sound/direct_sound_samples/sc88pro_string_ensemble_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_60::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_72::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_trumpet_84::
	.incbin "sound/direct_sound_samples/sc88pro_trumpet_84.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_39:: @N.B.: These tuba samples are actually sampled at 36 and 48, then pitched up
	.incbin "sound/direct_sound_samples/sc88pro_tuba_39.bin"

	.align 2
DirectSoundWaveData_sc88pro_tuba_51::
	.incbin "sound/direct_sound_samples/sc88pro_tuba_51.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_60::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_60.bin"

	.align 2
DirectSoundWaveData_sc88pro_french_horn_72::
	.incbin "sound/direct_sound_samples/sc88pro_french_horn_72.bin"

	.align 2
DirectSoundWaveData_sc88pro_flute::
	.incbin "sound/direct_sound_samples/sc88pro_flute.bin"

	.align 2
DirectSoundWaveData_sc88pro_fingered_bass::
	.incbin "sound/direct_sound_samples/sc88pro_fingered_bass.bin"

	.align 2
DirectSoundWaveData_unknown_koto_high::
	.incbin "sound/direct_sound_samples/unknown_koto_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_shakuhachi::
	.incbin "sound/direct_sound_samples/sd90_classical_shakuhachi.bin"

	.align 2
DirectSoundWaveData_unknown_koto_low::
	.incbin "sound/direct_sound_samples/unknown_koto_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_overdrive_guitar::
	.incbin "sound/direct_sound_samples/sd90_classical_overdrive_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_high::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_high.bin"

	.align 2
DirectSoundWaveData_sd90_classical_distortion_guitar_low::
	.incbin "sound/direct_sound_samples/sd90_classical_distortion_guitar_low.bin"

	.align 2
DirectSoundWaveData_heart_of_asia_gamelan::
	.incbin "sound/direct_sound_samples/heart_of_asia_gamelan.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_low::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_low.bin"

	.align 2
DirectSoundWaveData_sc88pro_church_organ3_high::
	.incbin "sound/direct_sound_samples/sc88pro_church_organ3_high.bin"

	.align 2
DirectSoundWaveData_unknown_female_voice::
	.incbin "sound/direct_sound_samples/unknown_female_voice.bin"

	.align 2
DirectSoundWaveData_unused_unknown_male_voice::
	.incbin "sound/direct_sound_samples/unused_unknown_male_voice.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_low::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_low.bin"

	.align 2
DirectSoundWaveData_sd90_classical_detuned_ep1_high::
	.incbin "sound/direct_sound_samples/sd90_classical_detuned_ep1_high.bin"

	.align 2
DirectSoundWaveData_sc88pro_timpani_with_snare::
	.incbin "sound/direct_sound_samples/sc88pro_timpani_with_snare.bin"

	.align 2
DirectSoundWaveData_unknown_synth_snare::
	.incbin "sound/direct_sound_samples/unknown_synth_snare.bin"

	.align 2
DirectSoundWaveData_sc88pro_square_wave::
	.incbin "sound/direct_sound_samples/sc88pro_square_wave.bin"

	.align 2
DirectSoundWaveData_bicycle_bell::
	.incbin "sound/direct_sound_samples/bicycle_bell.bin"

	.align 2
DirectSoundWaveData_8725A2C::
	.incbin "sound/direct_sound_samples/8725A2C.bin"

	.align 2
DirectSoundWaveData_sc88pro_pizzicato_strings::
	.incbin "sound/direct_sound_samples/sc88pro_pizzicato_strings.bin"

	.align 2
DirectSoundWaveData_872762C::
	.incbin "sound/direct_sound_samples/872762C.bin"

	.align 2
DirectSoundWaveData_872921C::
	.incbin "sound/direct_sound_samples/872921C.bin"

	.align 2
DirectSoundWaveData_872A5D0::
	.incbin "sound/direct_sound_samples/872A5D0.bin"

	.align 2
DirectSoundWaveData_sc88pro_wind::
	.incbin "sound/direct_sound_samples/sc88pro_wind.bin"

	.align 2
DirectSoundWaveData_sc88pro_bubbles::
	.incbin "sound/direct_sound_samples/sc88pro_bubbles.bin"

	.align 2
DirectSoundWaveData_872EEA8::
	.incbin "sound/direct_sound_samples/872EEA8.bin"

	.align 2
DirectSoundWaveData_87301B0::
	.incbin "sound/direct_sound_samples/87301B0.bin"

	.align 2
DirectSoundWaveData_trinity_30303_mega_bass::
	.incbin "sound/direct_sound_samples/trinity_30303_mega_bass.bin"

	.align 2
DirectSoundWaveData_8734298::
	.incbin "sound/direct_sound_samples/8734298.bin"

	.align 2
DirectSoundWaveData_87364A8::
	.incbin "sound/direct_sound_samples/87364A8.bin"

	.align 2
DirectSoundWaveData_sc88pro_tubular_bell::
	.incbin "sound/direct_sound_samples/sc88pro_tubular_bell.bin"

	.align 2
DirectSoundWaveData_87385E4::
	.incbin "sound/direct_sound_samples/87385E4.bin"

	.align 2
DirectSoundWaveData_trinity_big_boned::
	.incbin "sound/direct_sound_samples/trinity_big_boned.bin"

	.align 2
DirectSoundWaveData_sc88pro_harp::
	.incbin "sound/direct_sound_samples/sc88pro_harp.bin"

	.align 2
DirectSoundWaveData_sc88pro_xylophone::
	.incbin "sound/direct_sound_samples/sc88pro_xylophone.bin"

	.align 2
DirectSoundWaveData_873ECD8::
	.incbin "sound/direct_sound_samples/873ECD8.bin"

	.align 2
DirectSoundWaveData_8740818::
	.incbin "sound/direct_sound_samples/8740818.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion::
	.incbin "sound/direct_sound_samples/sc88pro_accordion.bin"

	.align 2
DirectSoundWaveData_87424B0::
	.incbin "sound/direct_sound_samples/87424B0.bin"

	.align 2
DirectSoundWaveData_87430C0::
	.incbin "sound/direct_sound_samples/87430C0.bin"

	.align 2
DirectSoundWaveData_8743C50::
	.incbin "sound/direct_sound_samples/8743C50.bin"

	.align 2
DirectSoundWaveData_87446EC::
	.incbin "sound/direct_sound_samples/87446EC.bin"

	.align 2
DirectSoundWaveData_8745034::
	.incbin "sound/direct_sound_samples/8745034.bin"

	.align 2
DirectSoundWaveData_8745A7C::
	.incbin "sound/direct_sound_samples/8745A7C.bin"

    .align 2
Cry_Venap::
    .incbin "sound/direct_sound_samples/cries/bulbasaur.bin"

    .align 2
Cry_Traplent::
    .incbin "sound/direct_sound_samples/cries/ivysaur.bin"

    .align 2
Cry_Dionare::
    .incbin "sound/direct_sound_samples/cries/venusaur.bin"

    .align 2
Cry_Celsinge::
    .incbin "sound/direct_sound_samples/cries/charmander.bin"

    .align 2
Cry_Fahramane::
    .incbin "sound/direct_sound_samples/cries/charmeleon.bin"

    .align 2
Cry_Kelvoyant::
    .incbin "sound/direct_sound_samples/cries/charizard.bin"

    .align 2
Cry_Echoise::
    .incbin "sound/direct_sound_samples/cries/squirtle.bin"

    .align 2
Cry_Mermeidon::
    .incbin "sound/direct_sound_samples/cries/wartortle.bin"

    .align 2
Cry_Dolphure::
    .incbin "sound/direct_sound_samples/cries/blastoise.bin"

    .align 2
Cry_Firant::
    .incbin "sound/direct_sound_samples/cries/caterpie.bin"

    .align 2
Cry_Pyroon::
    .incbin "sound/direct_sound_samples/cries/metapod.bin"

    .align 2
Cry_Pyreign::
    .incbin "sound/direct_sound_samples/cries/butterfree.bin"

    .align 2
Cry_Fincherp::
    .incbin "sound/direct_sound_samples/cries/pidgey.bin"

    .align 2
Cry_Gashawk::
    .incbin "sound/direct_sound_samples/cries/pidgeotto.bin"

    .align 2
Cry_Eaglair::
    .incbin "sound/direct_sound_samples/cries/pidgeot.bin"

    .align 2
Cry_Mogel::
    .incbin "sound/direct_sound_samples/cries/rattata.bin"

    .align 2
Cry_Firrel::
    .incbin "sound/direct_sound_samples/cries/raticate.bin"

    .align 2
Cry_Ampure::
    .incbin "sound/direct_sound_samples/cries/pikachu.bin"

    .align 2
Cry_Ohmure::
    .incbin "sound/direct_sound_samples/cries/raichu.bin"

    .align 2
Cry_Sandshrew::
    .incbin "sound/direct_sound_samples/cries/sandshrew.bin"

    .align 2
Cry_Sandslash::
    .incbin "sound/direct_sound_samples/cries/sandslash.bin"

    .align 2
Cry_Lupine::
    .incbin "sound/direct_sound_samples/cries/nidoran_f.bin"

    .align 2
Cry_Canileaf::
    .incbin "sound/direct_sound_samples/cries/nidorina.bin"

    .align 2
Cry_Wolvine::
    .incbin "sound/direct_sound_samples/cries/nidoqueen.bin"

    .align 2
Cry_Jalsida::
    .incbin "sound/direct_sound_samples/cries/pinsir.bin"

    .align 2
Cry_Spoink::
    .incbin "sound/direct_sound_samples/cries/spoink.bin"

    .align 2
Cry_Grumpig::
    .incbin "sound/direct_sound_samples/cries/grumpig.bin"

    .align 2
Cry_Spidream::
    .incbin "sound/direct_sound_samples/cries/spinarak.bin"

    .align 2
Cry_Arachmare::
    .incbin "sound/direct_sound_samples/cries/ariados.bin"

    .align 2
Cry_Pineco::
    .incbin "sound/direct_sound_samples/cries/pineco.bin"

    .align 2
Cry_Forretress::
    .incbin "sound/direct_sound_samples/cries/forretress.bin"

    .align 2
Cry_Embear::
    .incbin "sound/direct_sound_samples/cries/teddiursa.bin"

    .align 2
Cry_Grizlare::
    .incbin "sound/direct_sound_samples/cries/ursaring.bin"

    .align 2
Cry_Mankey::
    .incbin "sound/direct_sound_samples/cries/mankey.bin"

    .align 2
Cry_Primeape::
    .incbin "sound/direct_sound_samples/cries/primeape.bin"

    .align 2
Cry_Mareep::
    .incbin "sound/direct_sound_samples/cries/mareep.bin"

    .align 2
Cry_Flaaffy::
    .incbin "sound/direct_sound_samples/cries/flaaffy.bin"

    .align 2
Cry_Ampharos::
    .incbin "sound/direct_sound_samples/cries/ampharos.bin"

    .align 2
Cry_Whispaw::
    .incbin "sound/direct_sound_samples/cries/numel.bin"

    .align 2
Cry_Coroona::
    .incbin "sound/direct_sound_samples/cries/camerupt.bin"

    .align 2
Cry_Moocalf::
    .incbin "sound/direct_sound_samples/cries/miltank.bin"

    .align 2
Cry_Tauros::
    .incbin "sound/direct_sound_samples/cries/tauros.bin"

    .align 2
Cry_Miltank::
    .incbin "sound/direct_sound_samples/cries/miltank.bin"

    .align 2
Cry_Inflare::
    .incbin "sound/direct_sound_samples/cries/slugma.bin"

    .align 2
Cry_Ingero::
    .incbin "sound/direct_sound_samples/cries/magcargo.bin"

    .align 2
Cry_Drowzee::
    .incbin "sound/direct_sound_samples/cries/drowzee.bin"

    .align 2
Cry_Hypno::
    .incbin "sound/direct_sound_samples/cries/hypno.bin"

    .align 2
Cry_Cleffa::
    .incbin "sound/direct_sound_samples/cries/cleffa.bin"

    .align 2
Cry_Clefairy::
    .incbin "sound/direct_sound_samples/cries/clefairy.bin"

    .align 2
Cry_Clefable::
    .incbin "sound/direct_sound_samples/cries/clefable.bin"

    .align 2
Cry_Grific::
    .incbin "sound/direct_sound_samples/cries/hoothoot.bin"

    .align 2
Cry_Gryphonic::
    .incbin "sound/direct_sound_samples/cries/noctowl.bin"

    .align 2
Cry_Barkub::
    .incbin "sound/direct_sound_samples/cries/growlithe.bin"

    .align 2
Cry_Growlithe::
    .incbin "sound/direct_sound_samples/cries/growlithe.bin"

    .align 2
Cry_Arcanine::
    .incbin "sound/direct_sound_samples/cries/arcanine.bin"

    .align 2
Cry_Vixun::
    .incbin "sound/direct_sound_samples/cries/vulpix.bin"

    .align 2
Cry_Vulpix::
    .incbin "sound/direct_sound_samples/cries/vulpix.bin"

    .align 2
Cry_Ninetales::
    .incbin "sound/direct_sound_samples/cries/ninetales.bin"

    .align 2
Cry_Kondria::
    .incbin "sound/direct_sound_samples/cries/sneasel.bin"

    .align 2
Cry_Whismur::
    .incbin "sound/direct_sound_samples/cries/whismur.bin"

    .align 2
Cry_Loudred::
    .incbin "sound/direct_sound_samples/cries/loudred.bin"

    .align 2
Cry_Exploud::
    .incbin "sound/direct_sound_samples/cries/exploud.bin"

    .align 2
Cry_Stribra::
    .incbin "sound/direct_sound_samples/cries/manectric.bin"

    .align 2
Cry_Murkrow::
    .incbin "sound/direct_sound_samples/cries/murkrow.bin"

    .align 2
Cry_Harskrow::
    .incbin "sound/direct_sound_samples/cries/golbat.bin"

    .align 2
Cry_Jackalant::
    .incbin "sound/direct_sound_samples/cries/oddish.bin"

    .align 2
Cry_Phantern::
    .incbin "sound/direct_sound_samples/cries/vileplume.bin"

    .align 2
Cry_Skalloy::
    .incbin "sound/direct_sound_samples/cries/skarmory.bin"

    .align 2
Cry_Skarmory::
    .incbin "sound/direct_sound_samples/cries/skarmory.bin"

    .align 2
Cry_Duskull::
    .incbin "sound/direct_sound_samples/cries/duskull.bin"

    .align 2
Cry_Dusclops::
    .incbin "sound/direct_sound_samples/cries/dusclops.bin"

    .align 2
Cry_Cascadet::
    .incbin "sound/direct_sound_samples/cries/luvdisc.bin"

    .align 2
Cry_Venonat::
    .incbin "sound/direct_sound_samples/cries/venonat.bin"

    .align 2
Cry_Venomoth::
    .incbin "sound/direct_sound_samples/cries/venomoth.bin"

    .align 2
Cry_Smallard::
    .incbin "sound/direct_sound_samples/cries/wooper.bin"

    .align 2
Cry_Mallarge::
    .incbin "sound/direct_sound_samples/cries/quagsire.bin"

    .align 2
Cry_Grimer::
    .incbin "sound/direct_sound_samples/cries/grimer.bin"

    .align 2
Cry_Muk::
    .incbin "sound/direct_sound_samples/cries/muk.bin"

    .align 2
Cry_Koffing::
    .incbin "sound/direct_sound_samples/cries/koffing.bin"

    .align 2
Cry_Weezing::
    .incbin "sound/direct_sound_samples/cries/weezing.bin"

    .align 2
Cry_Zangoose::
    .incbin "sound/direct_sound_samples/cries/zangoose.bin"

    .align 2
Cry_Zantilidae::
    .incbin "sound/direct_sound_samples/cries/zangoose.bin"

    .align 2
Cry_Seviper::
    .incbin "sound/direct_sound_samples/cries/seviper.bin"

    .align 2
Cry_Pythang::
    .incbin "sound/direct_sound_samples/cries/seviper.bin"

    .align 2
Cry_Meowth::
    .incbin "sound/direct_sound_samples/cries/meowth.bin"

    .align 2
Cry_Persian::
    .incbin "sound/direct_sound_samples/cries/persian.bin"

    .align 2
Cry_Lotad::
    .incbin "sound/direct_sound_samples/cries/lotad.bin"

    .align 2
Cry_Lombre::
    .incbin "sound/direct_sound_samples/cries/lombre.bin"

    .align 2
Cry_Ludicolo::
    .incbin "sound/direct_sound_samples/cries/ludicolo.bin"

    .align 2
Cry_Trillogill::
    .incbin "sound/direct_sound_samples/cries/clamperl.bin"

    .align 2
Cry_Tidasale::
    .incbin "sound/direct_sound_samples/cries/gorebyss.bin"

    .align 2
Cry_Quiisord::
    .incbin "sound/direct_sound_samples/cries/huntail.bin"

    .align 2
Cry_Tsunall::
    .incbin "sound/direct_sound_samples/cries/huntail.bin"

    .align 2
Cry_Yanma::
    .incbin "sound/direct_sound_samples/cries/yanma.bin"

    .align 2
Cry_Slowpoke::
    .incbin "sound/direct_sound_samples/cries/slowpoke.bin"

    .align 2
Cry_Slowbro::
    .incbin "sound/direct_sound_samples/cries/slowbro.bin"

    .align 2
Cry_Slowking::
    .incbin "sound/direct_sound_samples/cries/slowking.bin"

    .align 2
Cry_Slowpriest::
    .incbin "sound/direct_sound_samples/cries/slowking.bin"

    .align 2
Cry_Remoraid::
    .incbin "sound/direct_sound_samples/cries/remoraid.bin"

    .align 2
Cry_Octillery::
    .incbin "sound/direct_sound_samples/cries/octillery.bin"

    .align 2
Cry_Phantasomo::
    .incbin "sound/direct_sound_samples/cries/misdreavus.bin"

    .align 2
Cry_Smeargle::
    .incbin "sound/direct_sound_samples/cries/smeargle.bin"

    .align 2
Cry_Seraph::
    .incbin "sound/direct_sound_samples/cries/dunsparce.bin"

    .align 2
Cry_Dunsparce::
    .incbin "sound/direct_sound_samples/cries/dunsparce.bin"

    .align 2
Cry_Absol::
    .incbin "sound/direct_sound_samples/cries/absol.bin"

    .align 2
Cry_Abyssus::
    .incbin "sound/direct_sound_samples/cries/absol.bin"

    .align 2
Cry_Equill::
    .incbin "sound/direct_sound_samples/cries/taillow.bin"

    .align 2
Cry_Tellure::
    .incbin "sound/direct_sound_samples/cries/swellow.bin"

    .align 2
Cry_Corphish::
    .incbin "sound/direct_sound_samples/cries/corphish.bin"

    .align 2
Cry_Crawdaunt::
    .incbin "sound/direct_sound_samples/cries/crawdaunt.bin"

    .align 2
Cry_Ditto::
    .incbin "sound/direct_sound_samples/cries/ditto.bin"

    .align 2
Cry_Gargoth::
    .incbin "sound/direct_sound_samples/cries/onix.bin"

    .align 2
Cry_Cragoyle::
    .incbin "sound/direct_sound_samples/cries/steelix.bin"

    .align 2
Cry_Togepi::
    .incbin "sound/direct_sound_samples/cries/togepi.bin"

    .align 2
Cry_Togetic::
    .incbin "sound/direct_sound_samples/cries/togetic.bin"

    .align 2
Cry_Cirroft::
    .incbin "sound/direct_sound_samples/cries/castform.bin"

    .align 2
Cry_Cumuloft::
    .incbin "sound/direct_sound_samples/cries/castform.bin"

    .align 2
Cry_Destado::
    .incbin "sound/direct_sound_samples/cries/castform.bin"

    .align 2
Cry_Frostorm::
    .incbin "sound/direct_sound_samples/cries/castform.bin"

    .align 2
Cry_Nimbolt::
    .incbin "sound/direct_sound_samples/cries/castform.bin"

    .align 2
Cry_Drakodo::
    .incbin "sound/direct_sound_samples/cries/torkoal.bin"

    .align 2
Cry_Eevee::
    .incbin "sound/direct_sound_samples/cries/eevee.bin"

    .align 2
Cry_Vaporeon::
    .incbin "sound/direct_sound_samples/cries/vaporeon.bin"

    .align 2
Cry_Jolteon::
    .incbin "sound/direct_sound_samples/cries/jolteon.bin"

    .align 2
Cry_Flareon::
    .incbin "sound/direct_sound_samples/cries/flareon.bin"

    .align 2
Cry_Espeon::
    .incbin "sound/direct_sound_samples/cries/espeon.bin"

    .align 2
Cry_Umbreon::
    .incbin "sound/direct_sound_samples/cries/umbreon.bin"

    .align 2
Cry_Illumeon::
    .incbin "sound/direct_sound_samples/cries/jolteon.bin"

    .align 2
Cry_Chiarame::
    .incbin "sound/direct_sound_samples/cries/houndour.bin"

    .align 2
Cry_Serberine::
    .incbin "sound/direct_sound_samples/cries/houndoom.bin"

    .align 2
Cry_Misdreavus::
    .incbin "sound/direct_sound_samples/cries/misdreavus.bin"

    .align 2
Cry_Engil::
    .incbin "sound/direct_sound_samples/cries/swinub.bin"

    .align 2
Cry_Benengil::
    .incbin "sound/direct_sound_samples/cries/piloswine.bin"

    .align 2
Cry_Duval::
    .incbin "sound/direct_sound_samples/cries/poochyena.bin"

    .align 2
Cry_Malduval::
    .incbin "sound/direct_sound_samples/cries/mightyena.bin"

    .align 2
Cry_Qwilfish::
    .incbin "sound/direct_sound_samples/cries/qwilfish.bin"

    .align 2
Cry_Tangela::
    .incbin "sound/direct_sound_samples/cries/tangela.bin"

    .align 2
Cry_Tropius::
    .incbin "sound/direct_sound_samples/cries/tropius.bin"

    .align 2
Cry_Brontogon::
    .incbin "sound/direct_sound_samples/cries/tropius.bin"

    .align 2
Cry_Blitzfaust::
    .incbin "sound/direct_sound_samples/cries/hitmonchan.bin"

    .align 2
Cry_Vilephist::
    .incbin "sound/direct_sound_samples/cries/hitmonlee.bin"

    .align 2
Cry_Rhyhorn::
    .incbin "sound/direct_sound_samples/cries/rhyhorn.bin"

    .align 2
Cry_Rhydon::
    .incbin "sound/direct_sound_samples/cries/rhydon.bin"

    .align 2
Cry_Torkoal::
    .incbin "sound/direct_sound_samples/cries/torkoal.bin"

    .align 2
Cry_Sinestril::
    .incbin "sound/direct_sound_samples/cries/dratini.bin"

    .align 2
Cry_Malistril::
    .incbin "sound/direct_sound_samples/cries/dragonair.bin"

    .align 2
Cry_Scyther::
    .incbin "sound/direct_sound_samples/cries/scyther.bin"

    .align 2
Cry_Scizor::
    .incbin "sound/direct_sound_samples/cries/scizor.bin"

    .align 2
Cry_Bakurge::
    .incbin "sound/direct_sound_samples/cries/machamp.bin"

    .align 2
Cry_Lapras::
    .incbin "sound/direct_sound_samples/cries/lapras.bin"

    .align 2
Cry_Sirene::
    .incbin "sound/direct_sound_samples/cries/lapras.bin"

    .align 2
Cry_Iglonia::
    .incbin "sound/direct_sound_samples/cries/jynx.bin"

    .align 2
Cry_Stantler::
    .incbin "sound/direct_sound_samples/cries/stantler.bin"

    .align 2
Cry_Caribrisk::
    .incbin "sound/direct_sound_samples/cries/stantler.bin"

    .align 2
Cry_Huskii::
    .incbin "sound/direct_sound_samples/cries/spheal.bin"

    .align 2
Cry_Tundrolf::
    .incbin "sound/direct_sound_samples/cries/sealeo.bin"

    .align 2
Cry_Wolfrost::
    .incbin "sound/direct_sound_samples/cries/walrein.bin"

    .align 2
Cry_Reefrain::
    .incbin "sound/direct_sound_samples/cries/corsola.bin"

    .align 2
Cry_Polara::
    .incbin "sound/direct_sound_samples/cries/snorunt.bin"

    .align 2
Cry_Polarice::
    .incbin "sound/direct_sound_samples/cries/glalie.bin"

    .align 2
Cry_Mirust::
    .incbin "sound/direct_sound_samples/cries/gastly.bin"

    .align 2
Cry_Ferrian::
    .incbin "sound/direct_sound_samples/cries/haunter.bin"

    .align 2
Cry_Cacnea::
    .incbin "sound/direct_sound_samples/cries/cacnea.bin"

    .align 2
Cry_Cacturne::
    .incbin "sound/direct_sound_samples/cries/cacturne.bin"

    .align 2
Cry_Cackinge::
    .incbin "sound/direct_sound_samples/cries/cacturne.bin"

    .align 2
Cry_Scorchion::
    .incbin "sound/direct_sound_samples/cries/volbeat.bin"

    .align 2
Cry_Trapinch::
    .incbin "sound/direct_sound_samples/cries/trapinch.bin"

    .align 2
Cry_Vibrava::
    .incbin "sound/direct_sound_samples/cries/vibrava.bin"

    .align 2
Cry_Flygon::
    .incbin "sound/direct_sound_samples/cries/flygon.bin"

    .align 2
Cry_Staryu::
    .incbin "sound/direct_sound_samples/cries/staryu.bin"

    .align 2
Cry_Starmie::
    .incbin "sound/direct_sound_samples/cries/starmie.bin"

    .align 2
Cry_Corsola::
    .incbin "sound/direct_sound_samples/cries/corsola.bin"

    .align 2
Cry_Chinchou::
    .incbin "sound/direct_sound_samples/cries/chinchou.bin"

    .align 2
Cry_Lanturn::
    .incbin "sound/direct_sound_samples/cries/lanturn.bin"

    .align 2
Cry_Relicanth::
    .incbin "sound/direct_sound_samples/cries/relicanth.bin"

    .align 2
Cry_Misticade::
    .incbin "sound/direct_sound_samples/cries/misdreavus.bin"

    .align 2
Cry_Kraklaw::
    .incbin "sound/direct_sound_samples/cries/wailord.bin"

    .align 2
Cry_Leoracle::
    .incbin "sound/direct_sound_samples/cries/regirock.bin"

    .align 2
Cry_Khaphix::
    .incbin "sound/direct_sound_samples/cries/registeel.bin"

    .align 2
Cry_Flintusk::
    .incbin "sound/direct_sound_samples/cries/phanpy.bin"

    .align 2
Cry_Metusk::
    .incbin "sound/direct_sound_samples/cries/donphan.bin"

    .align 2
Cry_Allufang::
    .incbin "sound/direct_sound_samples/cries/anorith.bin"

    .align 2
Cry_Kunaiga::
    .incbin "sound/direct_sound_samples/cries/armaldo.bin"

    .align 2
Cry_Purior::
    .incbin "sound/direct_sound_samples/cries/hitmontop.bin"

    .align 2
Cry_Goldrake::
    .incbin "sound/direct_sound_samples/cries/magikarp.bin"

    .align 2
Cry_Arowana::
    .incbin "sound/direct_sound_samples/cries/gyarados.bin"

    .align 2
Cry_Atlaxa::
    .incbin "sound/direct_sound_samples/cries/larvitar.bin"

    .align 2
Cry_Thoraxa::
    .incbin "sound/direct_sound_samples/cries/pupitar.bin"

    .align 2
Cry_Illumbra::
    .incbin "sound/direct_sound_samples/cries/tyranitar.bin"

    .align 2
Cry_Snarliger::
    .incbin "sound/direct_sound_samples/cries/bagon.bin"

    .align 2
Cry_Noctiger::
    .incbin "sound/direct_sound_samples/cries/shelgon.bin"

    .align 2
Cry_Raiger::
    .incbin "sound/direct_sound_samples/cries/salamence.bin"

    .align 2
Cry_Matakite::
    .incbin "sound/direct_sound_samples/cries/raikou.bin"

    .align 2
Cry_Tagati::
    .incbin "sound/direct_sound_samples/cries/entei.bin"

    .align 2
Cry_Neichia::
    .incbin "sound/direct_sound_samples/cries/suicune.bin"

    .align 2
Cry_Kuranpu::
    .incbin "sound/direct_sound_samples/cries/celebi.bin"

    .align 2
Cry_Typhidna::
    .incbin "sound/direct_sound_samples/cries/groudon.bin"

    .align 2
Cry_Unicrown::
    .incbin "sound/direct_sound_samples/cries/rayquaza.bin"

    .align 2
Cry_Kipporok::
    .incbin "sound/direct_sound_samples/cries/mew.bin"

    .align 2
Cry_Jirachi::
    .incbin "sound/direct_sound_samples/cries/jirachi.bin"

	.align 2
DirectSoundWaveData_register_noise::
	.incbin "sound/direct_sound_samples/register_noise.bin"

	.align 2
DirectSoundWaveData_88D6978::
	.incbin "sound/direct_sound_samples/88D6978.bin"

	.align 2
DirectSoundWaveData_sc88pro_nylon_str_guitar::
	.incbin "sound/direct_sound_samples/sc88pro_nylon_str_guitar.bin"

	.align 2
DirectSoundWaveData_sd90_special_scream_drive::
	.incbin "sound/direct_sound_samples/sd90_special_scream_drive.bin"

	.align 2
DirectSoundWaveData_88DBBC0::
	.incbin "sound/direct_sound_samples/88DBBC0.bin"

	.align 2
DirectSoundWaveData_88DC220::
	.incbin "sound/direct_sound_samples/88DC220.bin"

	.align 2
DirectSoundWaveData_88DC704::
	.incbin "sound/direct_sound_samples/88DC704.bin"

	.align 2
DirectSoundWaveData_88DD054::
	.incbin "sound/direct_sound_samples/88DD054.bin"

	.align 2
DirectSoundWaveData_88DDAC4::
	.incbin "sound/direct_sound_samples/88DDAC4.bin"

	.align 2
DirectSoundWaveData_88DDDE4::
	.incbin "sound/direct_sound_samples/88DDDE4.bin"

	.align 2
DirectSoundWaveData_88DEA6C::
	.incbin "sound/direct_sound_samples/88DEA6C.bin"

	.align 2
DirectSoundWaveData_88DF08C::
	.incbin "sound/direct_sound_samples/88DF08C.bin"

	.align 2
DirectSoundWaveData_88DF414::
	.incbin "sound/direct_sound_samples/88DF414.bin"

	.align 2
DirectSoundWaveData_88E01F8::
	.incbin "sound/direct_sound_samples/88E01F8.bin"

	.align 2
DirectSoundWaveData_88E0B68::
	.incbin "sound/direct_sound_samples/88E0B68.bin"

	.align 2
DirectSoundWaveData_88E0F04::
	.incbin "sound/direct_sound_samples/88E0F04.bin"

	.align 2
DirectSoundWaveData_88E16B8::
	.incbin "sound/direct_sound_samples/88E16B8.bin"

	.align 2
DirectSoundWaveData_88E2414::
	.incbin "sound/direct_sound_samples/88E2414.bin"

	.align 2
DirectSoundWaveData_88E2658::
	.incbin "sound/direct_sound_samples/88E2658.bin"

	.align 2
DirectSoundWaveData_88E3498::
	.incbin "sound/direct_sound_samples/88E3498.bin"

	.align 2
DirectSoundWaveData_88E3DEC::
	.incbin "sound/direct_sound_samples/88E3DEC.bin"

	.align 2
DirectSoundWaveData_88E4140::
	.incbin "sound/direct_sound_samples/88E4140.bin"

	.align 2
DirectSoundWaveData_88E4774::
	.incbin "sound/direct_sound_samples/88E4774.bin"

	.align 2
DirectSoundWaveData_88E53E0::
	.incbin "sound/direct_sound_samples/88E53E0.bin"

	.align 2
DirectSoundWaveData_88E5978::
	.incbin "sound/direct_sound_samples/88E5978.bin"

	.align 2
DirectSoundWaveData_88E647C::
	.incbin "sound/direct_sound_samples/88E647C.bin"

	.align 2
DirectSoundWaveData_88E6A80::
	.incbin "sound/direct_sound_samples/88E6A80.bin"

	.align 2
DirectSoundWaveData_88E6C78::
	.incbin "sound/direct_sound_samples/88E6C78.bin"

	.align 2
DirectSoundWaveData_88E75DC::
	.incbin "sound/direct_sound_samples/88E75DC.bin"

	.align 2
DirectSoundWaveData_88E8568::
	.incbin "sound/direct_sound_samples/88E8568.bin"

	.align 2
DirectSoundWaveData_88E8BA0::
	.incbin "sound/direct_sound_samples/88E8BA0.bin"

	.align 2
DirectSoundWaveData_88E9674::
	.incbin "sound/direct_sound_samples/88E9674.bin"

	.align 2
DirectSoundWaveData_88EA5B8::
	.incbin "sound/direct_sound_samples/88EA5B8.bin"

	.align 2
DirectSoundWaveData_88EAB30::
	.incbin "sound/direct_sound_samples/88EAB30.bin"

	.align 2
DirectSoundWaveData_88EB97C::
	.incbin "sound/direct_sound_samples/88EB97C.bin"

	.align 2
DirectSoundWaveData_88EC884::
	.incbin "sound/direct_sound_samples/88EC884.bin"

	.align 2
DirectSoundWaveData_88ED358::
	.incbin "sound/direct_sound_samples/88ED358.bin"

	.align 2
DirectSoundWaveData_88EDEEC::
	.incbin "sound/direct_sound_samples/88EDEEC.bin"

	.align 2
DirectSoundWaveData_88EE8C4::
	.incbin "sound/direct_sound_samples/88EE8C4.bin"

	.align 2
DirectSoundWaveData_88EEF04::
	.incbin "sound/direct_sound_samples/88EEF04.bin"

	.align 2
DirectSoundWaveData_88EF9E4::
	.incbin "sound/direct_sound_samples/88EF9E4.bin"

	.align 2
DirectSoundWaveData_88F0020::
	.incbin "sound/direct_sound_samples/88F0020.bin"

	.align 2
DirectSoundWaveData_88F0738::
	.incbin "sound/direct_sound_samples/88F0738.bin"

	.align 2
DirectSoundWaveData_88F1074::
	.incbin "sound/direct_sound_samples/88F1074.bin"

	.align 2
DirectSoundWaveData_88F1830::
	.incbin "sound/direct_sound_samples/88F1830.bin"

	.align 2
DirectSoundWaveData_88F1D94::
	.incbin "sound/direct_sound_samples/88F1D94.bin"

	.align 2
DirectSoundWaveData_88F2B08::
	.incbin "sound/direct_sound_samples/88F2B08.bin"

	.align 2
DirectSoundWaveData_88F2F84::
	.incbin "sound/direct_sound_samples/88F2F84.bin"

	.align 2
DirectSoundWaveData_88F3470::
	.incbin "sound/direct_sound_samples/88F3470.bin"

	.align 2
DirectSoundWaveData_88F3C38::
	.incbin "sound/direct_sound_samples/88F3C38.bin"

	.align 2
DirectSoundWaveData_88F4834::
	.incbin "sound/direct_sound_samples/88F4834.bin"

	.align 2
DirectSoundWaveData_88F4BAC::
	.incbin "sound/direct_sound_samples/88F4BAC.bin"

	.align 2
DirectSoundWaveData_88F5368::
	.incbin "sound/direct_sound_samples/88F5368.bin"

	.align 2
DirectSoundWaveData_88F5FCC::
	.incbin "sound/direct_sound_samples/88F5FCC.bin"

	.align 2
DirectSoundWaveData_88F6498::
	.incbin "sound/direct_sound_samples/88F6498.bin"

	.align 2
DirectSoundWaveData_sc88pro_accordion_duplicate::
	.incbin "sound/direct_sound_samples/sc88pro_accordion_duplicate.bin"

	.align 2
DirectSoundWaveData_steinway_b_piano::
	.incbin "sound/direct_sound_samples/steinway_b_piano.bin"

	.align 2
DirectSoundWaveData_sd90_classical_whistle::
	.incbin "sound/direct_sound_samples/sd90_classical_whistle.bin"

	.align 2
DirectSoundWaveData_sd90_enhanced_delay_shaku::
	.incbin "sound/direct_sound_samples/sd90_enhanced_delay_shaku.bin"
