#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#define TRAINER_NONE                         0

//=====================================================
// Rival #2
//=====================================================
#define TRAINER_BRADLEY_NEOBAY_1_VENAP       1
#define TRAINER_BRADLEY_NEOBAY_1_CELSINGE    2
#define TRAINER_BRADLEY_NEOBAY_1_ECHOISE     3

//=====================================================
// Route 201
//=====================================================
#define TRAINER_ALLEN                        4
#define TRAINER_GUS                          5

//=====================================================
// Route 202
//=====================================================
#define TRAINER_TYLER                        6
#define TRAINER_NOAH                         7
#define TRAINER_MAT                          8
#define TRAINER_JANICE                       9

//=====================================================
// Rival #2
//=====================================================
#define TRAINER_BRADLEY_NEOBAY_2_VENAP      10
#define TRAINER_BRADLEY_NEOBAY_2_CELSINGE   11
#define TRAINER_BRADLEY_NEOBAY_2_ECHOISE    12

//=====================================================
// Route 203
//=====================================================
#define TRAINER_REED                        13
#define TRAINER_RYAN                        14
#define TRAINER_ALBERTO                     15
#define TRAINER_CHARLIE                     16
#define TRAINER_CLIFTON                     17

//=====================================================
// Chartree Forest
//=====================================================
#define TRAINER_FRANKLIN                    18
#define TRAINER_MARVIN                      19
#define TRAINER_WALLY                       20
#define TRAINER_ZELDA                       21
#define TRAINER_SARAH                       22

//=====================================================
// Route 204
//=====================================================
#define TRAINER_AINA                        23
#define TRAINER_DERRICK                     24
#define TRAINER_LEXI                        25
#define TRAINER_BEATRICE                    26

//=====================================================
// Cranewing Gym
//=====================================================
#define TRAINER_SLADE                       27
#define TRAINER_LOLA                        28
#define TRAINER_FROY                        29

//=====================================================
// Route 204  Rocket Encounter
//=====================================================
#define TRAINER_SHOOK_1                     30
#define TRAINER_ALLARD_1                    31

//=====================================================
// Chartree Forest Rocket Encounter
//=====================================================
#define TRAINER_GRUNT_CHARTREE_1            32
#define TRAINER_GRUNT_CHARTREE_2            33
#define TRAINER_GRUNT_CHARTREE_3            34
#define TRAINER_BALFOUR_1                   35

//=====================================================
// Softwind City Orion Encounter
//=====================================================
#define TRAINER_WOLSEY_1                    36

//=====================================================
// Softwind City Gym
//=====================================================
#define TRAINER_YUKI                        37
#define TRAINER_NESSA                       38
#define TRAINER_BRANDYN                     39
#define TRAINER_GREGOR                      40
#define TRAINER_THERMA                      41

//=====================================================
// Alisa #1
//=====================================================
#define TRAINER_ALISA_1_VENAP               42
#define TRAINER_ALISA_1_CELSINGE            43
#define TRAINER_ALISA_1_ECHOISE             44

//=====================================================
// Route 205
//=====================================================
#define TRAINER_FRANCIS                     45
#define TRAINER_AMY_AND_ALLY                46
#define TRAINER_TRAVIS                      47
#define TRAINER_GWEN                        48
#define TRAINER_PERCY                       49
#define TRAINER_ISHMAEL                     50

//=====================================================
// Route 206
//=====================================================
#define TRAINER_MIKAEL                      51
#define TRAINER_JURGEN                      52
#define TRAINER_WINSTON                     53
#define TRAINER_ELI                         54
#define TRAINER_SIERRA                      55
#define TRAINER_WANDA                       56





































#define TRAINER_GABBY_AND_TY_6               57
#define TRAINER_LOLA_1                       58
#define TRAINER_AUSTINA                      59
#define TRAINER_UNUSED_1                     60
#define TRAINER_LOLA_2                       61
#define TRAINER_LOLA_3                       62
#define TRAINER_LOLA_4                       63
#define TRAINER_LOLA_5                       64
#define TRAINER_RICKY_1                      65
#define TRAINER_SIMON                        66
#define TRAINER_ED                           67
#define TRAINER_RICKY_2                      68
#define TRAINER_RICKY_3                      69
#define TRAINER_RICKY_4                      70
#define TRAINER_RICKY_5                      71
#define TRAINER_RANDALL                      72
#define TRAINER_PARKER                       73
#define TRAINER_GEORGE                       74
#define TRAINER_BERKE                        75
#define TRAINER_BRAXTON                      76
#define TRAINER_VINCENT                      77
#define TRAINER_LEROY                        78
#define TRAINER_WILTON_1                     79
#define TRAINER_EDGAR                        80
#define TRAINER_ALBERT                       81
#define TRAINER_SAMUEL                       82
#define TRAINER_VITO                         83
#define TRAINER_OWEN                         84
#define TRAINER_WILTON_2                     85
#define TRAINER_WILTON_3                     86
#define TRAINER_WILTON_4                     87
#define TRAINER_WILTON_5                     88
#define TRAINER_WARREN                       89
#define TRAINER_MARY                         90
#define TRAINER_ALEXIA                       91
#define TRAINER_JODY                         92
#define TRAINER_WENDY                        93
#define TRAINER_KEIRA                        94
#define TRAINER_BROOKE_1                     95
#define TRAINER_JENNIFER                     96
#define TRAINER_HOPE                         97
#define TRAINER_SHANNON                      98
#define TRAINER_MICHELLE                     99
#define TRAINER_CAROLINE                     100
#define TRAINER_JULIE                       101
#define TRAINER_BROOKE_2                    102
#define TRAINER_BROOKE_3                    103
#define TRAINER_BROOKE_4                    104
#define TRAINER_BROOKE_5                    105
#define TRAINER_PATRICIA                    106
#define TRAINER_KINDRA                      107
#define TRAINER_TAMMY                       108
#define TRAINER_VALERIE_1                   109
#define TRAINER_TASHA                       110
#define TRAINER_VALERIE_2                   111
#define TRAINER_VALERIE_3                   112
#define TRAINER_VALERIE_4                   113
#define TRAINER_VALERIE_5                   114
#define TRAINER_CINDY_1                     115
#define TRAINER_DAPHNE                      116
#define TRAINER_GRUNT_SPACE_CENTER_2        117
#define TRAINER_CINDY_2                     118
#define TRAINER_BRIANNA                     119
#define TRAINER_NAOMI                       120
#define TRAINER_CINDY_3                     121
#define TRAINER_CINDY_4                     122
#define TRAINER_CINDY_5                     123
#define TRAINER_CINDY_6                     124
#define TRAINER_MELISSA                     125
#define TRAINER_SHEILA                      126
#define TRAINER_SHIRLEY                     127
#define TRAINER_JESSICA_1                   128
#define TRAINER_CONNIE                      129
#define TRAINER_BRIDGET                     130
#define TRAINER_OLIVIA                      131
#define TRAINER_TIFFANY                     132
#define TRAINER_JESSICA_2                   133
#define TRAINER_JESSICA_3                   134
#define TRAINER_JESSICA_4                   135
#define TRAINER_JESSICA_5                   136
#define TRAINER_WINSTON_1                   137
#define TRAINER_MOLLIE                      138
#define TRAINER_GARRET                      139
#define TRAINER_WINSTON_2                   140
#define TRAINER_WINSTON_3                   141
#define TRAINER_WINSTON_4                   142
#define TRAINER_WINSTON_5                   143
#define TRAINER_STEVE_1                     144
#define TRAINER_THALIA_1                    145
#define TRAINER_MARK                        146
#define TRAINER_GRUNT_MT_CHIMNEY_1          147
#define TRAINER_STEVE_2                     148
#define TRAINER_STEVE_3                     149
#define TRAINER_STEVE_4                     150
#define TRAINER_STEVE_5                     151
#define TRAINER_LUIS                        152
#define TRAINER_DOMINIK                     153
#define TRAINER_DOUGLAS                     154
#define TRAINER_DARRIN                      155
#define TRAINER_TONY_1                      156
#define TRAINER_JEROME                      157
#define TRAINER_GRUNT_CHARTREE_3HEW         158
#define TRAINER_DAVID                       159
#define TRAINER_SPENCER                     160
#define TRAINER_ROLAND                      161
#define TRAINER_NOLEN                       162
#define TRAINER_STAN                        163
#define TRAINER_BARRY                       164
#define TRAINER_DEAN                        165
#define TRAINER_RODNEY                      166
#define TRAINER_RICHARD                     167
#define TRAINER_HERMAN                      168
#define TRAINER_SANTIAGO                    169
#define TRAINER_GILBERT                     170
#define TRAINER_DECLAN                      171
#define TRAINER_KEVIN                       172
#define TRAINER_JACK                        173
#define TRAINER_DUDLEY                      174
#define TRAINER_CHAD                        175
#define TRAINER_TONY_2                      176
#define TRAINER_TONY_3                      177
#define TRAINER_TONY_4                      178
#define TRAINER_TONY_5                      179
#define TRAINER_TAKAO                       180
#define TRAINER_HITOSHI                     181
#define TRAINER_KIYO                        182
#define TRAINER_KOICHI                      183
#define TRAINER_NOB_1                       184
#define TRAINER_NOB_2                       185
#define TRAINER_NOB_3                       186
#define TRAINER_NOB_4                       187
#define TRAINER_NOB_5                       188
#define TRAINER_YUJI                        189
#define TRAINER_DAISUKE                     190
#define TRAINER_ATSUSHI                     191
#define TRAINER_KIRK                        192
#define TRAINER_GRUNT_AQUA_HIDEOUT_7        193
#define TRAINER_GRUNT_AQUA_HIDEOUT_8        194
#define TRAINER_SHAWN                       195
#define TRAINER_FERNANDO_1                  196
#define TRAINER_DALTON_1                    197
#define TRAINER_DALTON_2                    198
#define TRAINER_DALTON_3                    199
#define TRAINER_DALTON_4                    200
#define TRAINER_DALTON_5                    201
#define TRAINER_COLE                        202
#define TRAINER_JEFF                        203
#define TRAINER_AXLE                        204
#define TRAINER_JACE                        205
#define TRAINER_KEEGAN                      206
#define TRAINER_BERNIE_1                    207
#define TRAINER_BERNIE_2                    208
#define TRAINER_BERNIE_3                    209
#define TRAINER_BERNIE_4                    210
#define TRAINER_BERNIE_5                    211
#define TRAINER_DREW                        212
#define TRAINER_BEAU                        213
#define TRAINER_LARRY                       214
#define TRAINER_SHANE                       215
#define TRAINER_JUSTIN                      216
#define TRAINER_ETHAN_1                     217
#define TRAINER_AUTUMN                      218
#define TRAINER_UNUSED_2                    219
#define TRAINER_ETHAN_2                     220
#define TRAINER_ETHAN_3                     221
#define TRAINER_ETHAN_4                     222
#define TRAINER_ETHAN_5                     223
#define TRAINER_BRENT                       224
#define TRAINER_DONALD                      225
#define TRAINER_TAYLOR                      226
#define TRAINER_JEFFREY_1                   227
#define TRAINER_DEREK                       228
#define TRAINER_JEFFREY_2                   229
#define TRAINER_JEFFREY_3                   230
#define TRAINER_JEFFREY_4                   231
#define TRAINER_JEFFREY_5                   232
#define TRAINER_EDWARD                      233
#define TRAINER_PRESTON                     234
#define TRAINER_VIRGIL                      235
#define TRAINER_BLAKE                       236
#define TRAINER_WILLIAM                     237
#define TRAINER_JOSHUA                      238
#define TRAINER_CAMERON_1                   239
#define TRAINER_CAMERON_2                   240
#define TRAINER_CAMERON_3                   241
#define TRAINER_CAMERON_4                   242
#define TRAINER_CAMERON_5                   243
#define TRAINER_JACLYN                      244
#define TRAINER_HANNAH                      245
#define TRAINER_SAMANTHA                    246
#define TRAINER_MAURA                       247
#define TRAINER_KAYLA                       248
#define TRAINER_ALEXIS                      249
#define TRAINER_JACKI_1                     250
#define TRAINER_JACKI_2                     251
#define TRAINER_JACKI_3                     252
#define TRAINER_JACKI_4                     253
#define TRAINER_JACKI_5                     254
#define TRAINER_WALTER_1                    255
#define TRAINER_MICAH                       256
#define TRAINER_THOMAS                      257
#define TRAINER_WALTER_2                    258
#define TRAINER_WALTER_3                    259
#define TRAINER_WALTER_4                    260
#define TRAINER_WALTER_5                    261
#define TRAINER_SIDNEY                      262
#define TRAINER_PHOEBE                      263
#define TRAINER_GLACIA                      264
#define TRAINER_DRAKE                       265
#define TRAINER_ROXANNE_1                   266
#define TRAINER_BRAWLY_1                    267
#define TRAINER_WATTSON_1                   268
#define TRAINER_FLANNERY_1                  269
#define TRAINER_NORMAN_1                    270
#define TRAINER_WINONA_1                    271
#define TRAINER_TATE_AND_LIZA_1             272
#define TRAINER_JUAN_1                      273
#define TRAINER_JERRY_1                     274
#define TRAINER_TED                         275
#define TRAINER_PAUL                        276
#define TRAINER_JERRY_2                     277
#define TRAINER_JERRY_3                     278
#define TRAINER_JERRY_4                     279
#define TRAINER_JERRY_5                     280
#define TRAINER_KAREN_1                     281
#define TRAINER_GEORGIA                     282
#define TRAINER_KAREN_2                     283
#define TRAINER_KAREN_3                     284
#define TRAINER_KAREN_4                     285
#define TRAINER_KAREN_5                     286
#define TRAINER_KATE_AND_JOY                287
#define TRAINER_ANNA_AND_MEG_1              288
#define TRAINER_ANNA_AND_MEG_2              289
#define TRAINER_ANNA_AND_MEG_3              290
#define TRAINER_ANNA_AND_MEG_4              291
#define TRAINER_ANNA_AND_MEG_5              292
#define TRAINER_VICTOR                      293
#define TRAINER_MIGUEL_1                    294
#define TRAINER_COLTON                      295
#define TRAINER_MIGUEL_2                    296
#define TRAINER_MIGUEL_3                    297
#define TRAINER_MIGUEL_4                    298
#define TRAINER_MIGUEL_5                    299
#define TRAINER_VICTORIA                    300
#define TRAINER_VANESSA                     301
#define TRAINER_BETHANY                     302
#define TRAINER_ISABEL_1                    303
#define TRAINER_ISABEL_2                    304
#define TRAINER_ISABEL_3                    305
#define TRAINER_ISABEL_4                    306
#define TRAINER_ISABEL_5                    307
#define TRAINER_TIMOTHY_1                   308
#define TRAINER_TIMOTHY_2                   309
#define TRAINER_TIMOTHY_3                   310
#define TRAINER_TIMOTHY_4                   311
#define TRAINER_TIMOTHY_5                   312
#define TRAINER_VICKY                       313
#define TRAINER_SHELBY_1                    314
#define TRAINER_SHELBY_2                    315
#define TRAINER_SHELBY_3                    316
#define TRAINER_SHELBY_4                    317
#define TRAINER_SHELBY_5                    318
#define TRAINER_CALVIN_1                    319
#define TRAINER_BILLY                       320
#define TRAINER_JOSH                        321
#define TRAINER_TOMMY                       322
#define TRAINER_JOEY                        323
#define TRAINER_BEN                         324
#define TRAINER_QUINCY                      325
#define TRAINER_KATELYNN                    326
#define TRAINER_JAYLEN                      327
#define TRAINER_DILLON                      328
#define TRAINER_CALVIN_2                    329
#define TRAINER_CALVIN_3                    330
#define TRAINER_CALVIN_4                    331
#define TRAINER_CALVIN_5                    332
#define TRAINER_EDDIE                       333
#define TRAINER_SAWYER_1                    334
#define TRAINER_TIMMY                       335
#define TRAINER_WALLACE                     336
#define TRAINER_ANDREW                      337
#define TRAINER_IVAN                        338
#define TRAINER_CLAUDE                      339
#define TRAINER_ELLIOT_1                    340
#define TRAINER_NED                         341
#define TRAINER_DALE                        342
#define TRAINER_NOLAN                       343
#define TRAINER_BARNY                       344
#define TRAINER_WADE                        345
#define TRAINER_CARTER                      346
#define TRAINER_ELLIOT_2                    347
#define TRAINER_ELLIOT_3                    348
#define TRAINER_ELLIOT_4                    349
#define TRAINER_ELLIOT_5                    350
#define TRAINER_RONALD                      351
#define TRAINER_JACOB                       352
#define TRAINER_ANTHONY                     353
#define TRAINER_BENJAMIN_1                  354
#define TRAINER_BENJAMIN_2                  355
#define TRAINER_BENJAMIN_3                  356
#define TRAINER_BENJAMIN_4                  357
#define TRAINER_BENJAMIN_5                  358
#define TRAINER_ABIGAIL_1                   359
#define TRAINER_JASMINE                     360
#define TRAINER_ABIGAIL_2                   361
#define TRAINER_ABIGAIL_3                   362
#define TRAINER_ABIGAIL_4                   363
#define TRAINER_ABIGAIL_5                   364
#define TRAINER_DYLAN_1                     365
#define TRAINER_DYLAN_2                     366
#define TRAINER_DYLAN_3                     367
#define TRAINER_DYLAN_4                     368
#define TRAINER_DYLAN_5                     369
#define TRAINER_MARIA_1                     370
#define TRAINER_MARIA_2                     371
#define TRAINER_MARIA_3                     372
#define TRAINER_MARIA_4                     373
#define TRAINER_MARIA_5                     374
#define TRAINER_CAMDEN                      375
#define TRAINER_DEMETRIUS                   376
#define TRAINER_ISAIAH_1                    377
#define TRAINER_PABLO_1                     378
#define TRAINER_CHASE                       379
#define TRAINER_ISAIAH_2                    380
#define TRAINER_ISAIAH_3                    381
#define TRAINER_ISAIAH_4                    382
#define TRAINER_ISAIAH_5                    383
#define TRAINER_ISOBEL                      384
#define TRAINER_DONNY                       385
#define TRAINER_TALIA                       386
#define TRAINER_KATELYN_1                   387
#define TRAINER_ALLISON                     388
#define TRAINER_KATELYN_2                   389
#define TRAINER_KATELYN_3                   390
#define TRAINER_KATELYN_4                   391
#define TRAINER_KATELYN_5                   392
#define TRAINER_NICOLAS_1                   393
#define TRAINER_NICOLAS_2                   394
#define TRAINER_NICOLAS_3                   395
#define TRAINER_NICOLAS_4                   396
#define TRAINER_NICOLAS_5                   397
#define TRAINER_AARON                       398
#define TRAINER_PERRY                       399
#define TRAINER_HUGH                        400
#define TRAINER_PHIL                        401
#define TRAINER_JARED                       402
#define TRAINER_HUMBERTO                    403
#define TRAINER_PRESLEY                     404
#define TRAINER_EDWARDO                     405
#define TRAINER_COLIN                       406
#define TRAINER_ROBERT_1                    407
#define TRAINER_BENNY                       408
#define TRAINER_CHESTER                     409
#define TRAINER_ROBERT_2                    410
#define TRAINER_ROBERT_3                    411
#define TRAINER_ROBERT_4                    412
#define TRAINER_ROBERT_5                    413
#define TRAINER_ALEX                        414
#define TRAINER_BECK                        415
#define TRAINER_YASU                        416
#define TRAINER_TAKASHI                     417
#define TRAINER_DIANNE                      418
#define TRAINER_JANI                        419
#define TRAINER_LAO_1                       420
#define TRAINER_LUNG                        421
#define TRAINER_LAO_2                       422
#define TRAINER_LAO_3                       423
#define TRAINER_LAO_4                       424
#define TRAINER_LAO_5                       425
#define TRAINER_JOCELYN                     426
#define TRAINER_LAURA                       427
#define TRAINER_CYNDY_1                     428
#define TRAINER_CORA                        429
#define TRAINER_PAULA                       430
#define TRAINER_CYNDY_2                     431
#define TRAINER_CYNDY_3                     432
#define TRAINER_CYNDY_4                     433
#define TRAINER_CYNDY_5                     434
#define TRAINER_MADELINE_1                  435
#define TRAINER_CLARISSA                    436
#define TRAINER_ANGELICA                    437
#define TRAINER_MADELINE_2                  438
#define TRAINER_MADELINE_3                  439
#define TRAINER_MADELINE_4                  440
#define TRAINER_MADELINE_5                  441
#define TRAINER_BEVERLY                     442
#define TRAINER_IMANI                       443
#define TRAINER_KYLA                        444
#define TRAINER_DENISE                      445
#define TRAINER_BETH                        446
#define TRAINER_TARA                        447
#define TRAINER_MISSY                       448
#define TRAINER_ALICE                       449
#define TRAINER_JENNY_1                     450
#define TRAINER_GRACE                       451
#define TRAINER_TANYA                       452
#define TRAINER_SHARON                      453
#define TRAINER_NIKKI                       454
#define TRAINER_BRENDA                      455
#define TRAINER_KATIE                       456
#define TRAINER_SUSIE                       457
#define TRAINER_KARA                        458
#define TRAINER_DANA                        459
#define TRAINER_SIENNA                      460
#define TRAINER_DEBRA                       461
#define TRAINER_LINDA                       462
#define TRAINER_KAYLEE                      463
#define TRAINER_LAUREL                      464
#define TRAINER_CARLEE                      465
#define TRAINER_JENNY_2                     466
#define TRAINER_JENNY_3                     467
#define TRAINER_JENNY_4                     468
#define TRAINER_JENNY_5                     469
#define TRAINER_HEIDI                       470
#define TRAINER_BECKY                       471
#define TRAINER_CAROL                       472
#define TRAINER_NANCY                       473
#define TRAINER_MARTHA                      474
#define TRAINER_DIANA_1                     475
#define TRAINER_CEDRIC                      476
#define TRAINER_IRENE                       477
#define TRAINER_DIANA_2                     478
#define TRAINER_DIANA_3                     479
#define TRAINER_DIANA_4                     480
#define TRAINER_DIANA_5                     481
#define TRAINER_AMY_AND_LIV_1               482
#define TRAINER_AMY_AND_LIV_2               483
#define TRAINER_GINA_AND_MIA_1              484
#define TRAINER_MIU_AND_YUKI                485
#define TRAINER_AMY_AND_LIV_3               486
#define TRAINER_GINA_AND_MIA_2              487
#define TRAINER_AMY_AND_LIV_4               488
#define TRAINER_AMY_AND_LIV_5               489
#define TRAINER_AMY_AND_LIV_6               490
#define TRAINER_HUEY                        491
#define TRAINER_EDMOND                      492
#define TRAINER_ERNEST_1                    493
#define TRAINER_DWAYNE                      494
#define TRAINER_PHILLIP                     495
#define TRAINER_LEONARD                     496
#define TRAINER_DUNCAN                      497
#define TRAINER_ERNEST_2                    498
#define TRAINER_ERNEST_3                    499
#define TRAINER_ERNEST_4                    500
#define TRAINER_ERNEST_5                    501
#define TRAINER_UNUSED_3                    502
#define TRAINER_ANNIKA                      503
#define TRAINER_JAZMYN                      504
#define TRAINER_JONAS                       505
#define TRAINER_KAYLEY                      506
#define TRAINER_AURON                       507
#define TRAINER_KELVIN                      508
#define TRAINER_MARLEY                      509
#define TRAINER_REYNA                       510
#define TRAINER_HUDSON                      511
#define TRAINER_CONOR                       512
#define TRAINER_EDWIN_1                     513
#define TRAINER_HECTOR                      514
#define TRAINER_TABITHA_MOSSDEEP            515
#define TRAINER_EDWIN_2                     516
#define TRAINER_EDWIN_3                     517
#define TRAINER_EDWIN_4                     518
#define TRAINER_EDWIN_5                     519
#define TRAINER_WALLY_VR_1                  520
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP    521
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP    522
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP    523
#define TRAINER_BRENDAN_ROUTE_103_TREECKO   524
#define TRAINER_BRENDAN_ROUTE_110_TREECKO   525
#define TRAINER_BRENDAN_ROUTE_119_TREECKO   526
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC   527
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC   528
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC   529
#define TRAINER_MAY_ROUTE_103_MUDKIP        530
#define TRAINER_MAY_ROUTE_110_MUDKIP        531
#define TRAINER_MAY_ROUTE_119_MUDKIP        532
#define TRAINER_MAY_ROUTE_103_TREECKO       533
#define TRAINER_MAY_ROUTE_110_TREECKO       534
#define TRAINER_MAY_ROUTE_119_TREECKO       535
#define TRAINER_MAY_ROUTE_103_TORCHIC       536
#define TRAINER_MAY_ROUTE_110_TORCHIC       537
#define TRAINER_MAY_ROUTE_119_TORCHIC       538
#define TRAINER_ISAAC_1                     539
#define TRAINER_DAVIS                       540
#define TRAINER_MITCHELL                    541
#define TRAINER_ISAAC_2                     542
#define TRAINER_ISAAC_3                     543
#define TRAINER_ISAAC_4                     544
#define TRAINER_ISAAC_5                     545
#define TRAINER_LYDIA_1                     546
#define TRAINER_HALLE                       547
#define TRAINER_GARRISON                    548
#define TRAINER_LYDIA_2                     549
#define TRAINER_LYDIA_3                     550
#define TRAINER_LYDIA_4                     551
#define TRAINER_LYDIA_5                     552
#define TRAINER_JACKSON_1                   553
#define TRAINER_LORENZO                     554
#define TRAINER_SEBASTIAN                   555
#define TRAINER_JACKSON_2                   556
#define TRAINER_JACKSON_3                   557
#define TRAINER_JACKSON_4                   558
#define TRAINER_JACKSON_5                   559
#define TRAINER_CATHERINE_1                 560
#define TRAINER_JENNA                       561
#define TRAINER_SOPHIA                      562
#define TRAINER_CATHERINE_2                 563
#define TRAINER_CATHERINE_3                 564
#define TRAINER_CATHERINE_4                 565
#define TRAINER_CATHERINE_5                 566
#define TRAINER_JULIO                       567
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5     568
#define TRAINER_GRUNT_UNUSED                569
#define TRAINER_GRUNT_MT_PYRE_4             570
#define TRAINER_GRUNT_JAGGED_PASS           571
#define TRAINER_MARC                        572
#define TRAINER_BRENDEN                     573
#define TRAINER_LILITH                      574
#define TRAINER_CRISTIAN                    575
#define TRAINER_SYLVIA                      576
#define TRAINER_LEONARDO                    577
#define TRAINER_ATHENA                      578
#define TRAINER_HARRISON                    579
#define TRAINER_GRUNT_MT_CHIMNEY_2          580
#define TRAINER_CLARENCE                    581
#define TRAINER_TERRY                       582
#define TRAINER_NATE                        583
#define TRAINER_KATHLEEN                    584
#define TRAINER_CLIFFORD                    585
#define TRAINER_NICHOLAS                    586
#define TRAINER_GRUNT_SPACE_CENTER_3        587
#define TRAINER_GRUNT_SPACE_CENTER_4        588
#define TRAINER_GRUNT_SPACE_CENTER_5        589
#define TRAINER_GRUNT_SPACE_CENTER_6        590
#define TRAINER_GRUNT_SPACE_CENTER_7        591
#define TRAINER_MACEY                       592
#define TRAINER_BRENDAN_RUSTBORO_TREECKO    593
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP     594
#define TRAINER_PAXTON                      595
#define TRAINER_ISABELLA                    596
#define TRAINER_GRUNT_WEATHER_INST_5        597
#define TRAINER_TABITHA_MT_CHIMNEY          598
#define TRAINER_JONATHAN                    599
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC    600
#define TRAINER_MAY_RUSTBORO_MUDKIP         601
#define TRAINER_MAXIE_MAGMA_HIDEOUT         602
#define TRAINER_MAXIE_MT_CHIMNEY            603
#define TRAINER_TIANA                       604
#define TRAINER_HALEY_1                     605
#define TRAINER_JANICE_2                    606
#define TRAINER_VIVI                        607
#define TRAINER_HALEY_2                     608
#define TRAINER_HALEY_3                     609
#define TRAINER_HALEY_4                     610
#define TRAINER_HALEY_5                     611
#define TRAINER_SALLY                       612
#define TRAINER_ROBIN                       613
#define TRAINER_ANDREA                      614
#define TRAINER_CRISSY                      615
#define TRAINER_RICK                        616
#define TRAINER_LYLE                        617
#define TRAINER_JOSE                        618
#define TRAINER_DOUG                        619
#define TRAINER_GREG                        620
#define TRAINER_KENT                        621
#define TRAINER_JAMES_1                     622
#define TRAINER_JAMES_2                     623
#define TRAINER_JAMES_3                     624
#define TRAINER_JAMES_4                     625
#define TRAINER_JAMES_5                     626
#define TRAINER_BRICE                       627
#define TRAINER_TRENT_1                     628
#define TRAINER_LENNY                       629
#define TRAINER_LUCAS_1                     630
#define TRAINER_ALAN                        631
#define TRAINER_CLARK                       632
#define TRAINER_ERIC                        633
#define TRAINER_LUCAS_2                     634
#define TRAINER_MIKE_1                      635
#define TRAINER_MIKE_2                      636
#define TRAINER_TRENT_2                     637
#define TRAINER_TRENT_3                     638
#define TRAINER_TRENT_4                     639
#define TRAINER_TRENT_5                     640
#define TRAINER_DEZ_AND_LUKE                641
#define TRAINER_LEA_AND_JED                 642
#define TRAINER_KIRA_AND_DAN_1              643
#define TRAINER_KIRA_AND_DAN_2              644
#define TRAINER_KIRA_AND_DAN_3              645
#define TRAINER_KIRA_AND_DAN_4              646
#define TRAINER_KIRA_AND_DAN_5              647
#define TRAINER_JOHANNA                     648
#define TRAINER_GERALD                      649
#define TRAINER_VIVIAN                      650
#define TRAINER_DANIELLE                    651
#define TRAINER_HIDEO                       652
#define TRAINER_KEIGO                       653
#define TRAINER_RILEY                       654
#define TRAINER_FLINT                       655
#define TRAINER_ASHLEY                      656
#define TRAINER_WALLY_MAUVILLE              657
#define TRAINER_WALLY_VR_2                  658
#define TRAINER_WALLY_VR_3                  659
#define TRAINER_WALLY_VR_4                  660
#define TRAINER_WALLY_VR_5                  661
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP     662
#define TRAINER_BRENDAN_LILYCOVE_TREECKO    663
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC    664
#define TRAINER_MAY_LILYCOVE_MUDKIP         665
#define TRAINER_MAY_LILYCOVE_TREECKO        666
#define TRAINER_MAY_LILYCOVE_TORCHIC        667
#define TRAINER_JONAH                       668
#define TRAINER_HENRY                       669
#define TRAINER_ROGER                       670
#define TRAINER_ALEXA                       671
#define TRAINER_RUBEN                       672
#define TRAINER_KOJI_1                      673
#define TRAINER_WAYNE                       674
#define TRAINER_AIDAN                       675
#define TRAINER_GRUNT_PETALBURG_WOODS       676
#define TRAINER_TISHA                       677
#define TRAINER_TORI_AND_TIA                678
#define TRAINER_KIM_AND_IRIS                679
#define TRAINER_TYRA_AND_IVY                680
#define TRAINER_MEL_AND_PAUL                681
#define TRAINER_JOHN_AND_JAY_1              682
#define TRAINER_JOHN_AND_JAY_2              683
#define TRAINER_JOHN_AND_JAY_3              684
#define TRAINER_JOHN_AND_JAY_4              685
#define TRAINER_JOHN_AND_JAY_5              686
#define TRAINER_RELI_AND_IAN                687
#define TRAINER_LILA_AND_ROY_1              688
#define TRAINER_LILA_AND_ROY_2              689
#define TRAINER_LILA_AND_ROY_3              690
#define TRAINER_LILA_AND_ROY_4              691
#define TRAINER_LILA_AND_ROY_5              692
#define TRAINER_LISA_AND_RAY                693
#define TRAINER_CHRIS                       694
#define TRAINER_DAWSON                      695
#define TRAINER_GRUNT_WEATHER_INST_3        696
#define TRAINER_DARIAN                      697
#define TRAINER_HAILEY                      698
#define TRAINER_CHANDLER                    699
#define TRAINER_KALEB                       700
#define TRAINER_JOSEPH                      701
#define TRAINER_ALYSSA                      702
#define TRAINER_MARCOS                      703
#define TRAINER_RHETT                       704
#define TRAINER_TYRON                       705
#define TRAINER_CELINA                      706
#define TRAINER_BIANCA                      707
#define TRAINER_HAYDEN                      708
#define TRAINER_SOPHIE                      709
#define TRAINER_COBY                        710
#define TRAINER_LAWRENCE                    711
#define TRAINER_WYATT                       712
#define TRAINER_ANGELINA                    713
#define TRAINER_KAI                         714
#define TRAINER_CHARLOTTE                   715
#define TRAINER_DEANDRE                     716
#define TRAINER_GRUNT_MAGMA_HIDEOUT_1       717
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2       718
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3       719
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4       720
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5       721
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6       722
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7       723
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8       724
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9       725
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10      726
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11      727
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12      728
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13      729
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14      730
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15      731
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16      732
#define TRAINER_TABITHA_MAGMA_HIDEOUT       733
#define TRAINER_DARCY                       734
#define TRAINER_MAXIE_MOSSDEEP              735
#define TRAINER_PETE                        736
#define TRAINER_ISABELLE                    737
#define TRAINER_ANDRES_1                    738
#define TRAINER_JOSUE                       739
#define TRAINER_CAMRON                      740
#define TRAINER_CORY_1                      741
#define TRAINER_CAROLINA                    742
#define TRAINER_ELIJAH                      743
#define TRAINER_CELIA                       744
#define TRAINER_BRYAN                       745
#define TRAINER_BRANDEN                     746
#define TRAINER_BRYANT                      747
#define TRAINER_SHAYLA                      748
#define TRAINER_KYRA                        749
#define TRAINER_JAIDEN                      750
#define TRAINER_ALIX                        751
#define TRAINER_HELENE                      752
#define TRAINER_MARLENE                     753
#define TRAINER_DEVAN                       754
#define TRAINER_JOHNSON                     755
#define TRAINER_MELINA                      756
#define TRAINER_BRANDI                      757
#define TRAINER_AISHA                       758
#define TRAINER_MAKAYLA                     759
#define TRAINER_FABIAN                      760
#define TRAINER_DAYTON                      761
#define TRAINER_RACHEL                      762
#define TRAINER_LEONEL                      763
#define TRAINER_CALLIE                      764
#define TRAINER_CALE                        765
#define TRAINER_MYLES                       766
#define TRAINER_PAT                         767
#define TRAINER_CRISTIN_1                   768
#define TRAINER_MAY_RUSTBORO_TREECKO        769
#define TRAINER_MAY_RUSTBORO_TORCHIC        770
#define TRAINER_ROXANNE_2                   771
#define TRAINER_ROXANNE_3                   772
#define TRAINER_ROXANNE_4                   773
#define TRAINER_ROXANNE_5                   774
#define TRAINER_BRAWLY_2                    775
#define TRAINER_BRAWLY_3                    776
#define TRAINER_BRAWLY_4                    777
#define TRAINER_BRAWLY_5                    778
#define TRAINER_WATTSON_2                   779
#define TRAINER_WATTSON_3                   780
#define TRAINER_WATTSON_4                   781
#define TRAINER_WATTSON_5                   782
#define TRAINER_FLANNERY_2                  783
#define TRAINER_FLANNERY_3                  784
#define TRAINER_FLANNERY_4                  785
#define TRAINER_FLANNERY_5                  786
#define TRAINER_NORMAN_2                    787
#define TRAINER_NORMAN_3                    788
#define TRAINER_NORMAN_4                    789
#define TRAINER_NORMAN_5                    790
#define TRAINER_WINONA_2                    791
#define TRAINER_WINONA_3                    792
#define TRAINER_WINONA_4                    793
#define TRAINER_WINONA_5                    794
#define TRAINER_TATE_AND_LIZA_2             795
#define TRAINER_TATE_AND_LIZA_3             796
#define TRAINER_TATE_AND_LIZA_4             797
#define TRAINER_TATE_AND_LIZA_5             798
#define TRAINER_JUAN_2                      799
#define TRAINER_JUAN_3                      800
#define TRAINER_JUAN_4                      801
#define TRAINER_JUAN_5                      802
#define TRAINER_ANGELO                      803
#define TRAINER_DARIUS                      804
#define TRAINER_STEVEN                      805
#define TRAINER_ANABEL                      806
#define TRAINER_TUCKER                      807
#define TRAINER_SPENSER                     808
#define TRAINER_GRETA                       809
#define TRAINER_NOLAND                      810
#define TRAINER_LUCY                        811
#define TRAINER_BRANDON                     812
#define TRAINER_ANDRES_2                    813
#define TRAINER_ANDRES_3                    814
#define TRAINER_ANDRES_4                    815
#define TRAINER_ANDRES_5                    816
#define TRAINER_CORY_2                      817
#define TRAINER_CORY_3                      818
#define TRAINER_CORY_4                      819
#define TRAINER_CORY_5                      820
#define TRAINER_PABLO_2                     821
#define TRAINER_PABLO_3                     822
#define TRAINER_PABLO_4                     823
#define TRAINER_PABLO_5                     824
#define TRAINER_KOJI_2                      825
#define TRAINER_KOJI_3                      826
#define TRAINER_KOJI_4                      827
#define TRAINER_KOJI_5                      828
#define TRAINER_CRISTIN_2                   829
#define TRAINER_CRISTIN_3                   830
#define TRAINER_CRISTIN_4                   831
#define TRAINER_CRISTIN_5                   832
#define TRAINER_FERNANDO_2                  833
#define TRAINER_FERNANDO_3                  834
#define TRAINER_FERNANDO_4                  835
#define TRAINER_FERNANDO_5                  836
#define TRAINER_SAWYER_2                    837
#define TRAINER_SAWYER_3                    838
#define TRAINER_SAWYER_4                    839
#define TRAINER_SAWYER_5                    840
#define TRAINER_GABRIELLE_2                 841
#define TRAINER_GABRIELLE_3                 842
#define TRAINER_GABRIELLE_4                 843
#define TRAINER_GABRIELLE_5                 844
#define TRAINER_THALIA_2                    845
#define TRAINER_THALIA_3                    846
#define TRAINER_THALIA_4                    847
#define TRAINER_THALIA_5                    848
#define TRAINER_MARIELA                     849
#define TRAINER_ALVARO                      850
#define TRAINER_EVERETT                     851
#define TRAINER_RED                         852
#define TRAINER_LEAF                        853
#define TRAINER_BRENDAN_PLACEHOLDER         854
#define TRAINER_MAY_PLACEHOLDER             855

// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      856
#define MAX_TRAINERS_COUNT                  864

#endif  // GUARD_CONSTANTS_OPPONENTS_H
