SunsetVillage_House2_MapScripts::
	.byte 0


SunsetVillage_House2_Boy::
	msgbox SunsetVillage_House2_Boy_Text_0, MSGBOX_NPC
	end


SunsetVillage_House2_LittleBoy::
	msgbox SunsetVillage_House2_LittleBoy_Text_0, MSGBOX_NPC
	end


SunsetVillage_House2_Boy_Text_0:
	.string "I'm one of the only young folks in town,\n"
	.string "so I always get stuck babysitting the\l"
	.string "grandchildren.\p"
	.string "I don't mind though.\n"
	.string "It pays well!$"

SunsetVillage_House2_LittleBoy_Text_0:
	.string "My grandpa went shopping for my\n"
	.string "birthday.\p"
	.string "I hope I get the new video game I asked\n"
	.string "for!\p"
	.string "Oh boy oh boy oh boy!$"
