CranewingCity_Glassworks_2F_MapScripts::
	.byte 0


CranewingCity_Glassworks_2F_Executive::
	msgbox CranewingCity_Glassworks_2F_Executive_Text_0, MSGBOX_NPC
	end


CranewingCity_Glassworks_2F_Tech::
	msgbox CranewingCity_Glassworks_2F_Tech_Text_0, MSGBOX_NPC
	end


CranewingCity_Glassworks_2F_TrashCan::
	msgbox CranewingCity_Glassworks_2F_TrashCan_Text_0, MSGBOX_SIGN
	end


CranewingCity_Glassworks_2F_TrashCanViewingArea::
	msgbox CranewingCity_Glassworks_2F_TrashCanViewingArea_Text_0, MSGBOX_SIGN
	end


CranewingCity_Glassworks_2F_TrashCanBusinessOffice::
	msgbox CranewingCity_Glassworks_2F_TrashCanBusinessOffice_Text_0, MSGBOX_SIGN
	end


CranewingCity_Glassworks_2F_Computer::
	msgbox CranewingCity_Glassworks_2F_Computer_Text_0, MSGBOX_SIGN
	end


CranewingCity_Glassworks_2F_Blueprint::
	msgbox CranewingCity_Glassworks_2F_Blueprint_Text_0, MSGBOX_SIGN
	end


CranewingCity_Glassworks_2F_Executive_Text_0:
	.string "Welcome to Cranewing Glassworks!\p"
	.string "Are you here with your parents?\p"
	.string "I have a meeting with an important\n"
	.string "client soon, so go find them.$"

CranewingCity_Glassworks_2F_Tech_Text_0:
	.string "This is the public viewing area.\p"
	.string "From here, you can watch the magic\n"
	.string "happen!\p"
	.string "It's not magic, though.\n"
	.string "It's science.$"

CranewingCity_Glassworks_2F_TrashCan_Text_0:
	.string "The trash can is freshly cleaned.$"

CranewingCity_Glassworks_2F_TrashCanViewingArea_Text_0:
	.string "There's a crumbled piece of paper\n"
	.string "covered in doodles.$"

CranewingCity_Glassworks_2F_TrashCanBusinessOffice_Text_0:
	.string "There are lots of crumbed notes with\n"
	.string "names and times.$"

CranewingCity_Glassworks_2F_Computer_Text_0:
	.string "The screen is showing a list of numbers\n"
	.string "and dates.\p"
	.string "Many of the dates are colored red.$"

CranewingCity_Glassworks_2F_Blueprint_Text_0:
	.string "The table is covered in schematics for\n"
	.string "glass objects.\p"
	.string "Each has several prices labeled, with\n"
	.string "many scratched out.$"
