Route201_House_MapScripts::
	.byte 0


Route201_House_Gentleman::
	msgbox Route201_House_Gentleman_Text_0, MSGBOX_NPC
	end


Route201_House_Gentleman_Text_0:
	.string "I had this cottage built as a vacation\n"
	.string "home where I can get away from city\l"
	.string "life.\p"
	.string "I also had the bridge repaired so I\n"
	.string "could get out for walks.\p"
	.string "I wonder if anyone else will use it?$"
