Route203_House_MapScripts::
	.byte 0


Route203_House_Woman1::
	msgbox Route203_House_Woman1_Text_0, MSGBOX_NPC
	end


Route203_House_Woman2::
	msgbox Route203_House_Woman2_Text_0, MSGBOX_NPC
	end


Route203_House_Woman1_Text_0:
	.string "My wife is incredible with plants.\n"
	.string "There is nothing more wonderful than\l"
	.string "watching someone you love succeed!\p"
	.string "Here, why don't you take this?\p"
	.string "It'll help your Pokémon grow closer to\n"
	.string "you.$"

Route203_House_Woman2_Text_0:
	.string "There is something so fulfilling about\n"
	.string "surrounding yourself with growing\l"
	.string "things.\p"
	.string "It's my second greatest joy in life.$"
