SunsetVillage_House1_MapScripts::
	.byte 0


SunsetVillage_House1_OldMan::
# 11 "data/maps/SunsetVillage_House1/scripts.pory"
	msgbox SunsetVillage_House1_OldMan_Text_0, MSGBOX_NPC
	end


SunsetVillage_House1_OldMan_Text_0:
# 11 "data/maps/SunsetVillage_House1/scripts.pory"
	.string "My granddaughter left years ago to\n"
	.string "become a Pokémon Trainer.\p"
	.string "Now she lives in a big city on the coast!\p"
	.string "I'm so proud of her, but I miss her\n"
	.string "often.$"
