Route201_ItemPotion::
	finditem ITEM_POTION
	end


Route201_ItemSurfSpot::
	finditem ITEM_POTION
	end


Route202_ItemByFatMan::
	finditem ITEM_POTION
	end


Route202_ItemNorthCorner::
	finditem ITEM_POTION
	end


Route203_ItemOldRod::
	finditem ITEM_OLD_ROD
	end


Route203_ItemNorthGrass::
	finditem ITEM_POTION
	end


ChartreeForest_ItemLedge::
	finditem ITEM_POTION
	end


ChartreeForest_ItemCorner::
	finditem ITEM_POTION
	end


Route204_ItemDeadEnd::
	finditem ITEM_POTION
	end


Cranewing_West::
	finditem ITEM_POTION
	end


Cranewing_North::
	finditem ITEM_POTION
	end

