Route201_ItemPotion::
	finditem ITEM_POTION
	end


Route201_ItemSurfSpot::
	finditem ITEM_TM65_ZIGZAG
	end


Route202_ItemByFatMan::
	finditem ITEM_POKE_BALL
	end


Route202_ItemNorthCorner::
	finditem ITEM_REVIVE
	end


Route203_ItemOldRod::
	finditem ITEM_OLD_ROD
	end


Route203_ItemNorthGrass::
	finditem ITEM_SUPER_POTION
	end


Route203_ItemFarmhouse::
	finditem ITEM_X_DEFEND
	end


ChartreeForest_ItemLedge::
	finditem ITEM_BURN_HEAL
	end


ChartreeForest_ItemCorner::
	finditem ITEM_ETHER
	end


Route204_ItemDeadEnd::
	finditem ITEM_REPEL
	end


Cranewing_West::
	finditem ITEM_GREAT_BALL
	end


Cranewing_North::
	finditem ITEM_X_SP_DEF
	end


Route205_ItemSurfSpot::
	finditem ITEM_NUGGET
	end


Route205_ItemCorner::
	finditem ITEM_AWAKENING
	return

