Route201_ItemPotion::
# 5 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_POTION
	end


Route201_ItemSurfSpot::
# 10 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_TM_ZIGZAG
	end


Route202_ItemByFatMan::
# 15 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_POKE_BALL
	end


Route202_ItemNorthCorner::
# 20 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_REVIVE
	end


Route203_ItemOldRod::
# 25 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_OLD_ROD
	end


Route203_ItemNorthGrass::
# 30 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_SUPER_POTION
	end


Route203_ItemFarmhouse::
# 35 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_X_DEFEND
	end


ChartreeForest_ItemLedge::
# 40 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_BURN_HEAL
	end


ChartreeForest_ItemCorner::
# 45 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_ETHER
	end


Route204_ItemDeadEnd::
# 50 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_REPEL
	end


Cranewing_West::
# 55 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_GREAT_BALL
	end


Cranewing_North::
# 60 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_X_SP_DEF
	end


Route205_ItemSurfSpot::
# 65 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_NUGGET
	end


Route205_ItemCorner::
# 70 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_AWAKENING
	return


Route206_ItemFlowers::
# 74 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_POTION
	return


Route206_ItemSouth::
# 78 "data/scripts/item_ball_scripts_2.pory"
	finditem ITEM_X_SPEED
	return

