Route205_MapScripts::
	.byte 0


Route205_RichBoy::
	msgbox Route205_Text_RichBoy, MSGBOX_NPC
	end


Route205_Girl::
	msgbox Route205_Text_Girl, MSGBOX_NPC
	end


Route205_Scientist::
	msgbox Route205_Text_Scientist, MSGBOX_NPC
	end


Route205_Woman::
	msgbox Route205_Text_Woman, MSGBOX_NPC
	end


Route205_Text_RichBoy::
	.string "My friend and I are arguing about what\n"
	.string "Therma will bring back this time.\p"
	.string "I just know it's going to be new\n"
	.string "histories for the library!$"

Route205_Text_Girl::
	.string "My friend just cannot stop gossiping\n"
	.string "about what Therma will bring back.\p"
	.string "But since you asked, I am certain it will\n"
	.string "be new research papers!$"

Route205_Text_Scientist::
	.string "The best time of every season is\n"
	.string "waiting for Therma's new books!\p"
	.string "I am giddy as a Gashawk right now!$"

Route205_Text_Woman::
	.string "I've been waiting to challenge Therma\n"
	.string "since before she left!\p"
	.string "The first time I battled her she won\n"
	.string "handily…\p"
	.string "She's incredibly strong!\p"
	.string "This time is going to be different,\n"
	.string "though!$"
